<?php
/**
* Implementation of hook_feeds_plugins().
*/
function feeds_afgparser_feeds_plugins() {
  $info = array();
  $info['FeedsAFGParser'] = array(
    'name' => 'AllForGood Footprint XML Parser',
    'description' => 'Parses custom tags of Footprint XML (used in an AllForGood feed). Requires SimplePie.',
    'handler' => array(
      'parent' => 'FeedsSimplePieParser', // A plugin needs to derive either directly or indirectly from FeedsFetcher, FeedsParser or FeedsProcessor.
      'class' => 'FeedsAFGParser',
      'file' => 'FeedsAFGParser.inc',
      'path' => drupal_get_path('module', 'feeds_afgparser'),
    ),
  );
  return $info;
}

function feeds_afgparser_enable() {
  // clear the cache to display in Feeds as available plugin.
  cache_clear_all('plugins:feeds:plugins', 'cache');
}